[phases.setup]
packages = ["python3", "python3-pip", "python3-venv"]

[phases.install]
commands = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
    "echo 'Python app ready'"
]

[phases.start]
command = "gunicorn config.wsgi"
