[phases.setup]
packages = ["python310", "python310Packages.pip", "nodejs", "npm"]

[phases.install]
commands = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
    "echo 'Building static files'",
    "npm ci",
    "npm run build"
]

[phases.start]
command = "gunicorn config.wsgi"
