[project]
name = "dropme"
start = "gunicorn config.wsgi"

[[phases.setup.packages]]
name = "python"
version = "3.12"

[[phases.setup.packages]]
name = "node"
version = "20"

[[phases.setup.packages]]
name = "npm"

[[phases.setup.commands]]
command = "python3 -m pip install --upgrade pip"

[[phases.setup.commands]]
command = "python3 -m pip install -r requirements.txt"
