# Generated by Django 5.2.4 on 2025-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturing_year', models.IntegerField(blank=True, null=True)),
                ('seat_arrangement', models.IntegerField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, default=True, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('daily_services', models.BooleanField(blank=True, null=True)),
                ('rental_services', models.BooleanField(blank=True, null=True)),
                ('outstation_services', models.BooleanField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='driver_documents/licenses/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='driver_documents/id_proofs/')),
                ('vehicle_rc', models.FileField(blank=True, null=True, upload_to='driver_documents/vehicle_rcs/')),
            ],
        ),
    ]
