# Generated by Django 5.2.4 on 2025-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
