# Generated by Django 5.2.4 on 2025-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_driver_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="id_proof_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_document_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_rc_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
