# Generated by Django 5.2.4 on 2025-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_usage', models.IntegerField(blank=True, null=True)),
                ('max_usage_per_user', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Percent', 'Percent')], max_length=10, null=True)),
            ],
        ),
    ]
