# Generated by Django 5.2.4 on 2025-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="percentage_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage discount for percentage-based promo codes",
                max_digits=5,
                null=True,
            ),
        ),
    ]
