# Generated by Django 5.2.4 on 2026-02-17 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
