# Generated by Django 5.2.4 on 2025-07-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'rental_package',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.BooleanField(blank=True, null=True)),
                ('daily_service', models.BooleanField(blank=True, null=True)),
                ('rental_service', models.BooleanField(blank=True, null=True)),
                ('outstation_service', models.BooleanField(blank=True, null=True)),
                ('provider_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('driver_cash_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'servicetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.rentalpackage')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
        ),
    ]
