# Generated by Django 5.2.4 on 2025-08-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FareSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("km_from", models.DecimalField(decimal_places=2, max_digits=6)),
                ("km_to", models.DecimalField(decimal_places=2, max_digits=6)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("booking_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rate_per_minute",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "provider_commission",
                    models.DecimalField(decimal_places=2, default=90.0, max_digits=5),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_slabs",
                        to="services.servicetype",
                    ),
                ),
            ],
            options={
                "db_table": "fare_slab",
            },
        ),
    ]
