# Generated by Django 5.2.4 on 2025-08-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_fareslab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fareslab",
            name="provider_commission",
        ),
        migrations.RemoveField(
            model_name="fareslab",
            name="tax_percentage",
        ),
    ]
