# Generated by Django 5.2.4 on 2025-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturing_year', models.IntegerField(blank=True, null=True)),
                ('seat_arrangement', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
