# Generated by Django 5.2.4 on 2025-08-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("driver", "0002_driver_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="driver.driver",
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="driver.driver",
            ),
        ),
    ]
