# Generated by Django 5.2.4 on 2025-08-11 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_driver_alter_riderequest_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="scheduled_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
