# Generated by Django 5.2.4 on 2025-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_riderequest_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
