# Generated by Django 5.2.4 on 2025-08-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
