# Generated by Django 5.2.4 on 2025-12-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_ridepin"),
        ("booking", "0005_riderequest_payment_mode"),
    ]

    operations = []
