# Generated by Django 5.2.4 on 2026-01-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_merge_0002_ridepin_0005_riderequest_payment_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Arrived", "Arrived"),
                    ("Ongoing", "Ongoing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ridepin",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
